"""Resync from production state

Revision ID: e8c7d572acc0
Revises: 
Create Date: 2025-05-17 11:33:59.834393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e8c7d572acc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_app_meta_data', JSONB(), nullable=True),
    sa.Column('raw_user_meta_data', JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('starting_air', sa.Integer(), nullable=True),
    sa.Column('ending_air', sa.Integer(), nullable=True),
    sa.Column('dive_start_time', sa.DateTime(), nullable=True),
    sa.Column('dive_duration', sa.Integer(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('water_temperature', sa.Float(), nullable=True),
    sa.Column('wetsuit_thickness', sa.Integer(), nullable=True),
    sa.Column('wetsuit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weights', sa.Float(), nullable=True),
    sa.Column('fish_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['dive_id'], ['dives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dive_id')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('thumbnails', sa.JSON(), nullable=True),
    sa.Column('state', sa.Enum('PROCESSING', 'READY', name='mediaitemstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dive_id'], ['dives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_items')
    op.drop_table('logs')
    op.drop_table('dives')
    op.drop_table('users')
    # ### end Alembic commands ###
